name: Package Application with Pyinstaller

on:
  push:
    branches: [ pyinstaller_tests ]

jobs:
  build:

    if: contains(github.event.head_commit.message, 'Release v')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Create Release
      id: create_release  
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        tag_name: ${{ github.event.head_commit.message }}
        release_name: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/dist/windows/cta_matrix_iv.exe  # Adjust this if needed
        asset_name: cta_matrix_iv.exe  # Adjust this if needed
        asset_content_type: application/octet-stream
