name: Package Application with Pyinstaller

on:
  push:
    branches: [ pyinstaller_tests ]
  pull_request:
    branches: [ pyinstaller_tests ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile src/cta_matrix_iv.py
      shell: cmd

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/main.exe
        